version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    networks: 
      - frontend
      - backend
  backend:
    build: 
      context: ./backend
    ports:
      - "6000:6000"
    environment:
      - port=6000
    networks: 
      - frontend
      - backend
  ngnix:
    build: ./nginx
    ports:
      - "8080:80"
    networks: 
      - frontend
      - backend
networks: 
  frontend:
  backend: